name: Build
on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'repository revision'
        required: false
        default: 'master'
      target:
        description: 'build target'
        required: true
      build_amd64:
        description: 'Build on amd64'
        required: false
        default:  false
        type: boolean
      build_arm64:
        description: 'Build on arm64'
        required: false
        default:  true
        type: boolean
      build_macos:
        description: 'Build on macOS'
        required: false
        default:  false
        type: boolean
jobs:
  build:
    if: github.actor == 'roshanrags'
    name: Build
    strategy:
      matrix:
        runs-on:
        - 'ubicloud-standard-8'
        - 'ubicloud-standard-8-arm'
        - 'macos-latest'
        exclude:
        # If build_macos is false, this becomes 'macos-latest' and excludes the job.
        # If true, it evaluates to an empty string and excludes nothing.
        - runs-on: ${{ !inputs.build_macos && 'macos-latest' || '' }}
        - runs-on: ${{ !inputs.build_amd64 && 'ubicloud-standard-8' || '' }}
        - runs-on: ${{ !inputs.build_arm64 && 'ubicloud-standard-8-arm' || '' }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: echo
      run: |
        echo revision ${{ inputs.revision }}
    - name: Install Nix
      uses: cachix/install-nix-action@v30
    - name: Cachix
      uses: cachix/cachix-action@v15
      with:
        name: marlin
        authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
        useDaemon: false
    - name: permissions
      run: |
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        sudo sysctl -w kernel.unprivileged_userns_clone=1
    - name: build
      run: nix build -vL --accept-flake-config github:marlinprotocol/marlin/${{ inputs.revision }}#${{ inputs.target }}
